Sprint 1
drozdovdn/middle.messenger.praktikum.yandex pull request #2
Opened 2022-01-13 21:56 UTC by drozdovdn

2022-01-14 14:11 UTC, DmitryKhitrin requested changes
Спасибо за вашу работу, все выглядит очень не плохо, за исключением форматирования в некоторых местах.

Но к сожалению я не нашел ссылки на netlify, так что работу возвращаю

2022-01-14 14:11 UTC, khitrind commented on .postcssrc
> +}
Для git важно что бы файл заканчивался пустой строчкой)

https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-01-14 14:11 UTC, khitrind commented on index.json
> +}
EOF

2022-01-14 14:11 UTC, khitrind commented on index.ts
> +const PORT = 3000;
Часто удобно иметь возможность прокинуть порт снаружи:

`const port = process.env.PORT || PORT;`

2022-01-14 14:11 UTC, khitrind commented on src/components/button/button.ts
> +    return compile(buttonTmpl, {name, className})
Что-то страшное произошло с форматированием(

```
export const Button: ButtonProps = ({name, className = ''}) => {
    return compile(buttonTmpl, {name, className});
};
```

2022-01-14 14:11 UTC, khitrind commented on src/components/button/button.tmpl.ts
> +
Кажется тут лишний перенос строки

2022-01-14 14:11 UTC, khitrind commented on src/components/input/input.ts
> +export const Input: InputProps = ({
поехало форматирование

2022-01-14 14:11 UTC, DmitryKhitrin commented on src/features/addAvatarModal/addAvatarModal.ts
> +        const nameLabel = document.querySelector('.add-avatar-modal__name')
[querySelector](https://developer.mozilla.org/ru/docs/Web/API/Document/querySelector#возвращаемое_значение) может вернуть null, так что перед использованием, стоит проверить, что элемент существует:

```
const nameLabel = document.querySelector('.add-avatar-modal__name');

if (nameLabel) {
    // do smth
}

```

TS не подсветил из-за `:HTMLInputElement`

2022-01-14 14:11 UTC, khitrind commented on src/utils/last.ts
> +export const last = (mass: any[]) => {
Тут лучше сделать не через any, а через generic:

```
export const last = <T,>(mass: T[]) => {
    if (Array.isArray(mass)) {
        return mass[mass.length - 1];
    }
};
```

2022-01-14 14:11 UTC, khitrind commented on src/utils/get.ts
> +export const get = (obj: object, path: string, defaultValue?: any):any => {
Вместо any стоит использовать [generic](https://www.typescriptlang.org/docs/handbook/2/generics.html)

2022-01-14 14:11 UTC, DmitryKhitrin commented on src/templater/index.ts
> +        if (key[1]) {
magic numbers лучше стоит вынести в константы с осмысленным названием, что бы в будущем самому не запутаться)

2022-01-15 10:05 UTC, drozdovdn commented
Привет, окей , а ссылка то есть внизу файла readme, "ссылка на deploy Netlify"

2022-01-15 20:32 UTC, DmitryKhitrin requested changes
Добавь пожалуйста ссылку на netlify, это один из пунктов ТЗ

2022-01-16 07:03 UTC, drozdovdn commented
> Добавь пожалуйста ссылку на netlify, это один из пунктов ТЗ
Привет, ссылка в файле readme на ветке main, я её переместил в начало файла, посмотри там пожалуйста

2022-01-16 08:59 UTC, DmitryKhitrin approved these changes
Спасибо за правки, работу принимаю)

2022-01-18 13:43 UTC, merged