Sprint 2
drozdovdn/middle.messenger.praktikum.yandex pull request #4
Opened 2022-02-09 07:49 UTC by drozdovdn

2022-02-10 07:39 UTC, DmitryKhitrin requested changes
Большое спасибо за вашу работу, верхнеуровнево все выглядит очень не плохо, но есть некоторые вопросы к мелочам. Постарался расписать их в комментах, посмотрите пожалуйста)

2022-02-10 07:39 UTC, khitrind commented on src/components/input/input.ts
> +  type?: string;
Почему тут получилось, что все поля не обязательные, такого же не может быть)

2022-02-10 07:39 UTC, khitrind commented on src/components/input/input.ts
> +    click?: (e?: Event) => void;
Функции обработчики Dom элементов, передают в колбек ивент. Если в ваших обработчиках, вы не используете этот параметр, то его можно не описывать)

2022-02-10 07:39 UTC, khitrind commented on src/components/inputForm/inputForm.ts
> +import './inputForm.less';
Стили принято подключать либо первым, либо последним импортом, не смешивая их с импортами js модулей;

2022-02-10 07:39 UTC, khitrind commented on src/index.ts
> +const root = document.querySelector('.root');
[querySelector](https://developer.mozilla.org/ru/docs/Web/API/Document/querySelector#%D0%B2%D0%BE%D0%B7%D0%B2%D1%80%D0%B0%D1%89%D0%B0%D0%B5%D0%BC%D0%BE%D0%B5_%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B5), может вернуть null, тут должна быть проверка на наличие элемента, странно, что TS не подсвечивает это как ошибку

2022-02-10 07:39 UTC, khitrind commented on src/pages/auth/modules/signIn/signIn.ts
> +  inputs: { [key: string]: string };
Для описания таких типов, существует хелпер [Record](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type): Record<string, string>

2022-02-10 07:39 UTC, khitrind commented on src/pages/auth/modules/signUp/signUp.ts
> +            if (Object.values(this.inputs).includes('')) {
Тут у меня возникло несколько вопросов:

- для чего нужна эта проверка?
- почему если она не проходит мы выбрасываем ошибку? Если это ожидаемое поведение, то тут будет достаточно простого логирования)

2022-02-10 07:39 UTC, khitrind commented on src/pages/chat/modules/inputMessage/inputMessage.less
> +  color: #FFFFFF;
Часто удобно вынести цвета в css переменные, таким образом мы добавляем в нашу верстку немного системности + упрощаем себе будущие рефакторинги. Ведь теперь придется править всего одну переменную, а не миллион мест использования)

2022-02-10 07:39 UTC, khitrind commented on src/pages/errors/errors.ts
> +        const _500 = document.querySelector('._500');
[querySelector](https://developer.mozilla.org/ru/docs/Web/API/Document/querySelector#%D0%B2%D0%BE%D0%B7%D0%B2%D1%80%D0%B0%D1%89%D0%B0%D0%B5%D0%BC%D0%BE%D0%B5_%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B5), может вернуть null, тут должна быть проверка на наличие элемента, странно, что TS не подсвечивает это как ошибку

2022-02-10 07:39 UTC, khitrind commented on src/pages/profile/modules/changePassword/changePassword.ts
> +    this.oldPassword = 'Q123456789'; //Временно, данные старого пароля
Так, совсем не хорошо получается, давай хотя бы в константу на уровень модуля вынесем)

2022-02-10 07:39 UTC, khitrind commented on src/utils/block.ts
> +export default class Block<P = any> {
props лучше типизировать через [[generics](https://www.typescriptlang.org/docs/handbook/2/generics.html)](https://www.typescriptlang.org/docs/handbook/2/generics.html), так будет возможность точно передать в базовый блок, тип пропсов наследников.

В общем виде должно получиться, что-то такое:


```
abstract class Block<Props extends {}> {
    private element: HTMLElement;
    private tagName: string;

    protected props: Props;

    public constructor(tagName: string = 'div', propsAndChildren: Props) {
        this.tagName = tagName;
        this.props = propsAndChildren;
    }
}

type ButtonProps = {
    onClick: () => {};
};

class Button extends Block<ButtonProps> {
    public constructor(props: ButtonProps) {
        super('div', props);
    }

    public onClick() {
        this.props.onClick();
    }
}

```

2022-02-10 07:39 UTC, khitrind commented on src/pages/profile/modules/changePassword/changePassword.ts
> +    if (target.classList.contains('input-error-settings')) {
Экономия на спичках, но тут было бы проще не проверять каждый раз вхождение элемента в массив, а просто завести флфжок `shouldShowError`

2022-02-10 07:39 UTC, khitrind commented on src/pages/profile/modules/settings/settings.ts
> +                  };
Тут как-будто немного логика перемешана. В моей голове валидатор либо живет внутри инпута и мы можем выбрать его через type, либо он передается снаружи отдельным полем. Далее внутри инпута уже действует свой алгоритм с валидацией на внутренний change. Данные в обработчик полученный в параметре он передает, только если они валидны, в store в каждый момент времени должны лежать корректные данные.

```
const target = e.target as HTMLInputElement;
const isValidName = isName(target.value);

if (isValidName) {
    onChange(name);
} else {
    // setError, do smth
}
```

2022-02-10 07:39 UTC, khitrind commented on src/utils/block.ts
> +  _componentDidMount(oldProps) {
Для приватных полей, существует модификатор доступа [private](https://www.typescriptlang.org/docs/handbook/classes.html#public-private-and-protected-modifiers), запрещающй доступ к полю класса снаружи.

2022-02-10 07:39 UTC, DmitryKhitrin commented on src/utils/event-bus.ts
> +// const bus = new EventBus<'click'| 'inputForm', {click: [MouseEvent]; inputForm: [InputEvent]}>()
Я бы предложил немного упростить схему и передавать в тип структуру:

```
type EventBusHandlers = Record<EventName, Handler>;
class EventBus<Events extends {[key: string]: (...args: any[]) => void}> {
    _events: {
        [K in keyof Events]?: Events[K][];
    } = {};
}
const bus = new EventBus<EventBusHandlers>();
```

Считать тип от объекта как ни крути приятней, чем от списочка)

2022-02-10 07:39 UTC, DmitryKhitrin commented on src/utils/http-transport.ts
> +};
Для описания списков констант в TS существует такой инструмент, как [enum](https://www.typescriptlang.org/docs/handbook/enums.html):
```suggestion
enum HttpMethods {
    GET = 'GET',
    POST = 'POST',
    PUT = 'PUT',
    DELETE = 'DELETE',
};
```
В качестве типа для `MethodProps` можно использовать `HttpMethods`

2022-02-10 07:39 UTC, DmitryKhitrin commented on src/utils/http-transport.ts
> +        xhr.open(method, url + queryStringify(data));
Согласно протоколу HTTP query параметры можно передавать не только с методом GET. Тут возможны несколько вариантов решения) Либо формировать url внутри методов get, post... Либо принимать в options два параметра:

- params - их мы перекладываем в query
- data - это поле передаем в body запроса (это поле мы не передаем из метода get)

2022-02-10 07:39 UTC, DmitryKhitrin commented on src/utils/http-transport.ts
> +      if (method === METHODS.GET || !data) {
Тут достаточно просто проверки на наличие data

2022-02-10 07:39 UTC, DmitryKhitrin commented on src/utils/http-transport.ts
> +  return result.slice(0, result.length - 1);
Тут можно немного попроще:

```
Object.entries({}).reduce((res, [name, value]) => {
    return `${res}${name}=${value}&`;
}, '?');
```
Но есть проблема, в вашем варианте, если кто-то передаст в параметре объект, на сервер мы отправим полную чушь( Так как `[object Object]` никакого значения в себе не несет. В данном случае стоит проверять значение, является ли оно объектом и если да, то преобразовывать его к строке `JSON.stringify(obj)`

2022-02-10 07:39 UTC, DmitryKhitrin commented on src/utils/http-transport.ts
> +export function fetchWithRetry(url: string, options: OptionsProps): Promise<unknown> {
Почему эта функция называется fetchWithRetry? По коду - это просто обертка над GET. В работе с ретраями тоже как-будто нет ничего особенного, так как это функционал включается через option, как и везде)

2022-02-10 07:39 UTC, DmitryKhitrin commented on tsconfig.json
> +    "target": "es5",                       /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
На учебном проекты я бы 100% рекомендовал выставить TS в строгий режим. Где еще учиться, как ни на учебном проекте)

2022-02-10 07:39 UTC, DmitryKhitrin commented on src/pages/profile/modules/changePassword/changePassword.ts
> +              disabled: false,
Такое свойство как disabled можно сделать необязательным, а в коде выставить значение по умолчанию)

2022-02-10 07:39 UTC, DmitryKhitrin commented on src/pages/profile/modules/changePassword/changePassword.ts
> +              disabled: false,
Все равно практически везде вы передаете туда именно false

2022-02-12 12:59 UTC, drozdovdn commented on src/pages/auth/modules/signUp/signUp.ts
> +            if (Object.values(this.inputs).includes('')) {
Условие пред отправкой еще раз проверяет что поля заполнены, а поп оводу ошибки наврено да лучше просто логирование

2022-02-12 13:17 UTC, drozdovdn commented on src/components/input/input.ts
> +    click?: (e?: Event) => void;
Использую но не везде

2022-02-12 19:57 UTC, khitrind approved these changes

2022-02-15 10:42 UTC, merged