Sprint 3
drozdovdn/middle.messenger.praktikum.yandex pull request #6
Opened 2022-06-06 11:41 UTC by drozdovdn

2022-06-06 14:20 UTC, podlovchenko requested changes
Привет, не смогла проверить работу приложения
1. Нет редиректа на страницу чатов, если пользователь уже в системе
2. Есть ошибки при сборке

2022-06-06 14:20 UTC, podlovchenko commented on package.json
> +    "@parcel/optimizer-data-url": "^2.5.0",
Чтобы не возникло ошибок из-за разных версий стоит указывать фиксированные версии зависимостей и добавлять в репозиторий package-lock.json
^ устанавливает последнюю минорную версию

2022-06-06 19:44 UTC, drozdovdn commented
Привет, я поправил, добавил package-lock.json, у меня был там редирект на страницу чатов, у меня стоит проверка на авторизован пользователь или нет и в заваисимости от этого редиретил на страницу чата, но я еще добавил проверку на странице авторизауии и регистрауии.

2022-06-08 07:42 UTC, podlovchenko commented
Через npm run start черный экран и ошибка в консоли
<img width="1790" alt="Снимок экрана 2022-06-08 в 10 41 52" src="https://user-images.githubusercontent.com/22602747/172560395-5c95ddc3-bddf-4aee-91fc-1753188827d6.png">

Запустилось через npm run dev, но нельзя открыть чат, ошибки в консоли
<img width="485" alt="Снимок экрана 2022-06-08 в 10 39 40" src="https://user-images.githubusercontent.com/22602747/172560222-358ebb6c-5cf5-4a57-a169-774d523b5e99.png">

На нетлифае
<img width="474" alt="Снимок экрана 2022-06-08 в 10 42 40" src="https://user-images.githubusercontent.com/22602747/172560549-1fb4b48d-b40b-4c3a-95cc-ace03bb63a99.png">

2022-06-09 13:04 UTC, drozdovdn commented
Привет, поправил, проверил вроде все работает как надо, поправил ссылку на Netlify и залил туда текушие изменения.

2022-06-10 08:20 UTC, podlovchenko commented
Привет, через npm run start так и не получилось запустить
Проверила на netlify, не грузится аватар

2022-06-10 09:51 UTC, drozdovdn commented
Закгрузку аватарки я попраил,
А что именно не получилось при запуске npm run start? что он выдает??
У меня все запускается, последовательность действий следущая:
- клонирую репозиторий
- перехожу на ветку sprint_3
- npm i
- npm run start
И у меня запускается и работает все =)

2022-06-10 10:05 UTC, podlovchenko commented
Делаю аналогично, но черный экран, странно
Обнови нетлифай, если с загрузкой аватара окей, то приму работу

2022-06-10 10:14 UTC, drozdovdn commented
Netlify обновил, на портале Яндкса повторно отправил работу на сдачу

2022-06-10 10:25 UTC, podlovchenko commented
<img width="361" alt="Снимок экрана 2022-06-10 в 13 25 18" src="https://user-images.githubusercontent.com/22602747/173046096-9ffc6d16-219b-4c42-a8f8-e65d8acbec84.png">

2022-06-10 10:58 UTC, drozdovdn commented
ок, сейчас проверю что не так

2022-06-10 11:36 UTC, drozdovdn commented
я немного там по другому сделал сейчас, у меня иконка отображается
можешь скнуть скрин куда ведет ссылка на в картинке? может картинка не доступна?
или может кеш почистить?
у меня во тод двумя разными аккаунтами показывается)
![image](https://user-images.githubusercontent.com/51026661/173056512-98050029-e8a9-4510-b1e7-909d63c7fd40.png)
![image](https://user-images.githubusercontent.com/51026661/173056591-b15832cf-a906-433d-ba7b-087372b2b194.png)

2022-06-10 13:30 UTC, podlovchenko commented
Проблема с названием файла была, файл, который я использовала для проверки обычно со стандартным названием скрина некорректно запрашивается у тебя, с другим названием сработало, это некритично
Работу принимаю

2022-06-18 17:48 UTC, merged